routes/web.php
<?php

use \App\Pelicula;
use App\Productor; 
use App\Genero; 

Route::get('/test3', function () {
  $pelicula = Pelicula::first();
  

  $pelicula->productora()->dissociate();
  $pelicula->save();
  return $pelicula;

});

 
 
Route::get('/test2', function () { 

/*    

  $productor = new Productor;     
  $productor->nombre = "Sony";     
  $productor->save(); 
 
    $productor = new Productor;     
    $productor->nombre = "Disney";     
    $productor->save(); 
 
    $productor = new Productor;     
    $productor->nombre = "Fox";     
    $productor->save(); 
 
    $productor = new Productor; 
    $productor->nombre = "Warner Bros";  
    $productor->save(); 
 
    $productor = new Productor;     
    $productor->nombre = "MGM";     
    $productor->save(); 
 
    $genero = new Genero;     
    $genero->identificador = 'accion';     
    $genero->nombre = 'Acción';     
    $genero->save(); 
 
    $genero = new Genero;     
    $genero->identificador = 'comedia';     
    $genero->nombre = 'Comedia';     
    $genero->save(); 
 
    $genero = new Genero;     
    $genero->identificador = 'drama';     
    $genero->nombre = 'Drama';     
    $genero->save(); 
 
    $genero = new Genero;     
    $genero->identificador = 'terror';     
    $genero->nombre = 'Terror';     
    $genero->save(); 

    */

    return Pelicula::select('peliculas.*')->join('productoras','productoras.id','=','peliculas.productora_id')
    ->where('productoras.nombre', 'Sony')->get();




  }); 

Route::get('/pagprueba', function () {

return View::make('principal');


  //crear registro
	// $pelicula=new Pelicula;
 //  $pelicula->identificador='rambo';
 //  $pelicula->titulo='Rambo';
 //  $pelicula->ano=1982;
 //  $pelicula->save();

  
//cambiar registro
  //$pelicula->titulo = 'Acorralado';
  //$pelicula->save();

//eliminar
  //$pelicula->delete();
  //Pelicula::destroy([2,3,4,5]);

 /* 
Pelicula::where('identificador', '=', 'rambo')->update([
       'titulo' => 'Acorralado',
       'identificador' => 'acorralado'

    ]);
    */

 //return Pelicula::take(2)->get();
  

  //$pelicula = Pelicula::find(3);
 // return $pelicula->titulo;

  //return Pelicula::rockySaga()->pluck('titulo');


    /*associar
   
  $pelicula = Pelicula::first();
  $productora = Productor::first();

  $pelicula->productora()->associate($productora);
  $pelicula->save();
  return $pelicula;
  */

  /* sincronizar tabla genero_pelicula
  $genero = Genero::first();

  $peliculas = [3,4,5,6,7];

  $genero->peliculas()->sync($peliculas);
  $genero->save();
  return $genero->peliculas;

  */




})->name('principal');


Route::get('/test4', function () {
  
  $productor = Productor::first();
  $pelicula = Pelicula::where('identificador', 'acorralado')->first();
  $pelicula2 = Pelicula::where('identificador', 'rocky')->first();
  $pelicula3 = Pelicula::where('identificador', 'creed')->first();
$productor->peliculas()->saveMany([$pelicula,$pelicula2,$pelicula3]);
$productor->save();

   });


Route::get('/test', function () {
  

  /*
 $pelicula = new Pelicula;
 $pelicula->identificador = "rambo";
 $pelicula->titulo = "Rambo";
 $pelicula->ano = 1982;
 $pelicula->save();
 $pelicula = new Pelicula;
 $pelicula->identificador = "rambo-ii";
 $pelicula->titulo = "Rambo II";
 $pelicula->ano = 1985;
 $pelicula->save();
 $pelicula = new Pelicula;
 $pelicula->identificador = "rambo-iii";
 $pelicula->titulo = "Rambo III";
 $pelicula->ano = 1988;
 $pelicula->save();
 $pelicula = new Pelicula;
 $pelicula->identificador = "john-rambo";
 $pelicula->titulo = "John Rambo";
 $pelicula->ano = 2008;
 $pelicula->save();
 $pelicula = new Pelicula;
 $pelicula->identificador = "rocky";
 $pelicula->titulo = "Rocky";
 $pelicula->ano = 1976;
 $pelicula->save();
 $pelicula = new Pelicula;
 $pelicula->identificador = "rocky-ii";
 $pelicula->titulo = "Rocky II";
 $pelicula->ano = 1979;
 $pelicula->save();
 $pelicula = new Pelicula;
 $pelicula->identificador = "rocky-iii";
 $pelicula->titulo = "Rocky III";
 $pelicula->ano = 1982;
 $pelicula->save();
 $pelicula = new Pelicula;
 $pelicula->identificador = "rocky-iv";
 $pelicula->titulo = "Rocky IV";
 $pelicula->ano = 1986;
 $pelicula->save();
 $pelicula = new Pelicula;
 $pelicula->identificador = "rocky-v";
 $pelicula->titulo = "Rocky V";
 $pelicula->ano = 1990;
 $pelicula->save();
 $pelicula = new Pelicula;
 $pelicula->identificador = "rocky-balboa";
 $pelicula->titulo = "Rocky Balboa";
 $pelicula->ano = 2006;
 $pelicula->save();
 $pelicula = new Pelicula;
 $pelicula->identificador = "creed";
 $pelicula->titulo = "Creed";
 $pelicula->ano = 2016;
 $pelicula->save();
 */

//$pelicula = Pelicula::find(3);
  //return Pelicula::where('ano', '=', 1982)->pluck('titulo');
  //return Pelicula::where('ano', '=', 1982)->where('titulo', 'Acorralado')->get();
$productor = Productor::first();
return $productor->peliculas()->where('ano', '<', 2000)->get();

});


Route::get('/segunda', function () {
 return Pelicula::whereNested(function($query)
 {
 $query->where('ano', '>', 2000);
 $query->where('identificador', 'LIKE', '%rambo%');
 })->orWhere(function ($query)
 {
 $query->where('ano', '<', 2000);
 $query->where('identificador', 'LIKE', '%rocky%');
 })->get();
})->name('segunda');


Route::get('/peliculas', function () {

 



})->name('peliculas');

Route::get('/creartoken',function(){
  $user=Auth::user();
  $token=$user->createToken('hola')->accessToken;
  return $token;

})->middleware('auth');




Route::resource('peliculas', 'PeliculaController');



Route::get('/formulario', function (){
  return View::make('formulario');
})->name('formulario');

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::get('/pruebusu', function(){
  if (Auth::check()) {
    return "autenticado";
  } else {
    return "no autenticado";
  }


})->middleware('auth')->name('home');

/*
Route::group(function(){
  Route::get('/formulario', function (){
  return View::make('formulario');
})->name('email');

})->middleware('auth')->prefix('pruebas')
*/

resources/views/basico.blade.php
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="utf-8">
	<title></title>
</head>
<body>

	<p>Holaaaaaaa</p>

</body>
</html>

resources/views/cabecera.blade.php
<h1 style="text-align: center;">Cabecera {{$title}}</h1>

resources/views/detail.blade.php
@extends('layouts.blade', ['title'=>'Película ' . $pelicula->titulo])

@section('body')
<center>
  <h2>Título: {{$pelicula->titulo}}</h2>
  <h3>Año: {{$pelicula->ano}}</h3>

@if ($pelicula->productora)
<p>
  Productora: {{$pelicula->productora->nombre}}
</p>
@endif

@if ($pelicula->generos && $pelicula->generos->count()>0)
   <p>
     Géneros: {{$pelicula->generos->implode('nombre',',')}}
   </p>
@endif

  @if ($pelicula->poster)
     <img src="{{url($pelicula->poster)}}"/>
  @endif
  @auth
  <p>
  	<a href="{{route('peliculas.edit',$pelicula)}}">Editar película</a>
  </p>
  @endauth

   <p>
  	<a href="{{route('peliculas.index',$pelicula)}}">Lista de películas</a>
  </p>
</center>

resources/views/edit.blade.php
@extends('layouts.blade', ['title'=>'Película '])

@section('body')

<center>
	<h1>
      Editar {{$pelicula->titulo}}
	</h1>

	<h2>
<a href="{{route('peliculas.index')}}">Lista de películas</a>
    </h2>
</center>

<form style="text-align: center;" action="{{route('peliculas.update',$pelicula)}}"" method="POST" enctype="multipart/form-data">
    	{{csrf_field()}}
    	{{method_field('PUT')}}
    	<p>
    		<label for="titulo">Título</label>
    		<input type="text" name="titulo" id="titulo" placeholder="Título"
    		value="{{old('titulo',$pelicula->titulo)}}">

    	</p>
    	<p>
    		<label for="ano">Año</label>
    		<input type="number" name="ano" id="ano" placeholder="Año"
    		value="{{old('ano',$pelicula->ano)}}">

    	</p>
      
      

      
      <center>  
    	<p>
    		<label for="poster">Poster</label>
    		<input type="file" name="poster" id="poster">

    	</p>
      <p>
      
      
      <label for="productora_id">Productora</label>
      
      <select name="productora_id">
        <option selected disabled>Seleccionar productora</option>
        @foreach ($productoras as $productora)
        <option value="{{$productora->id}}"
           @if (old('productora_id', $pelicula->productora_id)==$productora->id)
           selected
           @endif
           > {{$productora->nombre}}

          </option>
          @endforeach
        
         </select>


        </p>


        <p>
         <label for="pgeneros">Genero</label> 
          <select id="generos" name="generos[]" multiple>
        
        @foreach ($generos as $genero)
        <option value="{{$genero->id}}"
           @if (in_array($genero->id,old ('generos',$pelicula->generos->pluck('id')->toArray())))
           selected
           @endif
           > {{$genero->nombre}}

          </option>
          @endforeach
        
         </select> 

        </p>


      </center>

    	<p>
    		<button>Enviar</button>
    	</p>

    </form>

    <center>

    <form action="{{route('peliculas.destroy',$pelicula)}}"" method="POST">
   {{csrf_field()}}
   {{method_field('DELETE')}}


        <p>
         	<input type="submit" value="Eliminar">
    	</p>
    	

    </form>

    </center>
    @stop

resources/views/formulario.blade.php
@extends('layouts.blade', ['title' => 'Formulario']) 

@section('body')

   <h1 style="text-align: center;">Introducir película</h1>

   <center>

   <p><a href="{{route('peliculas.index')}}">Lista de películas</a></p>
     </center>
  
     @if ($errors->any())
           <div class="alert alert-danger">
           	<ul>
           		@foreach ($errors->all() as $error)
           		<li>{{$error}}</li>
                @endforeach

           	</ul>
           	

           </div>
     @endif


    <form style="text-align: center;" action="{{route('peliculas.store')}}"" method="POST" enctype="multipart/form-data">
    	{{csrf_field()}}
    	<p>
    		<label for="titulo">Título</label>
    		<input type="text" name="titulo" id="titulo" placeholder="Título"
    		value="{{old('titulo')}}">

    	</p>
    	<p>
    		<label for="ano">Año</label>
    		<input type="number" name="ano" id="ano" placeholder="Año"
    		value="{{old('ano')}}">

    	</p>
      
      

      
      <center>  
    	<p>
    		<label for="poster">Poster</label>
    		<input type="file" name="poster" id="poster">

    	</p>
      <p>
      
      
      <label for="productora_id">Productora</label>
      

      <select name="productora_id">
        <option selected disabled>Seleccionar productora</option>
        @foreach ($productoras as $productora)
        <option value="{{$productora->id}}"
           @if (old('productora_id')==$productora->id)
           selected
           @endif
           > {{$productora->nombre}}

          </option>
          @endforeach
        
         </select>


        </p>


        <p>
         <label for="pgeneros">Genero</label> 
          <select id="generos" name="generos[]" multiple>
        
        @foreach ($generos as $genero)
        <option value="{{$genero->id}}"
           @if (old('generos') && in_array($genero->id, old('generos')))
           selected
           @endif
           > {{$genero->nombre}}

          </option>
          @endforeach
        
         </select> 




        </p>


      </center>




    	<p>
    		<button>Enviar</button>
    	</p>


    </form>

@stop

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
@extends('layouts.app', ['title'=>'Peliculas'])

@section('content')

<!DOCTYPE html>
<html>
<head>
	<title>Películas</title>
	<h1 style="text-align: center;">Películas</h1>
    <h2>
    
    <center>
    <a href="{{route('principal')}}">Página principal</a>
     </center>

      </h2>
</head>
<body>
    <center>
    <table style="align-content: center;" border="1">
    	<tr>
    		<td>
    			<p>Título</p>
    		</td>
    		<td>
    			<p>Año</p>
    		</td>
            @auth
    		<td>
    			<p>Editar</p>
    		</td>
            @endauth

    	</tr>
    	@foreach ($pelicula->all() as $pelicula)
    	<tbody>  	
    	<tr>
    		<td>
    			
    			<a href="{{route('peliculas.show',$pelicula)}}">{{$pelicula->titulo}}</a>

    		</td>
    	    		
    		<td>
    			
    			{{$pelicula->ano}}

    		</td>
            @auth
    		<td>
                
    			<a href="{{route('peliculas.edit', $pelicula)}}">Editar</a>
                
    		</td>
            @endauth
    	</tr>
    	</tbody>
    	@endforeach
        @auth
    	<a href="{{route('peliculas.create')}}">Crear película</a>	
        @endauth
    </table>

    </center>
    @stop

</body>
</html>

resources/views/larga.blade.php
@extends('layouts.blade', ['title'=> 'Página que no sirve para nada'])
@section('body')
<a href="{{route('formulario')}}">Página principal</a>

@stop

resources/views/peliculas.blade.php
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="utf-8">
	<title>Películas</title>
</head>
<body>
	
	@if ($genero=='cosas')
	<p>Rambo</p>
	@elseif ($genero=='comedia')
	<p>Condemor</p>
	@else
	<p>No hay</p>
	@endif
	

    <p>Peliculas de <strong>{{$genero}}</strong></p>
    <p><?=$prueba?></p>
    <p>{{date('d/m/y')}}</p>

    @include('pie')

</body>
</html>

resources/views/peliculas2.blade.php
@extends('layouts.blade', ['title' => 'Películas'])



@section('estilos')
@parent
<link rel="stylesheet" type="text/css" href="peliculas.css">
@stop

@section('body')
   <p>Películas de {{$genero}}</p>
 @stop

resources/views/pie.blade.php
<small style="text-align: center;">Pie</small>

resources/views/principal.blade.php
@extends('layouts.app', ['title'=>'Página principal'])

@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Peliculas</div>

                <div class="panel-body">
   



   <h1 style="text-align: center;">Página Principal</h1>

   <center>

     <h2>
  	<a href="{{route('peliculas.index')}}">Lista de películas</a>
      </h2>

      <img src="tot.png"/>

      </center>




                </div>
            </div>
        </div>
    </div>
</div>

@stop

resources/views/store.blade.php
@extends('layouts.blade', ['title'=>'Película '])

@section('body')

<a href="{{route('peliculas.index')}}">Lista de películas</a>